# 2019.05.01

## 1 Bug描述

这个Bug是编译成功后，遇到的第一个运行时Bug。

### 1.1 Bug复现

以3-124的服务器作为路径举例。

```bash
# Enter docker container
$ sudo docker start -ai c9_porting
# Run klee with single-process program
$ cd /home/chy/secProjects/lt_workspace/mpse/mpse_build
# "hello!" and 6 are the input of the testcase program
$ bin/klee -libc=uclibc -posix-runtime ../testcases/klee_testcases_from_huawei/bitcode_llvm34/pthread_base1_sp.bc "hello!" 6
```

### 1.2 Bug现象

然后就会看到Klee卡顿在一个地方，通过`htop`性能工具可以看到，Klee仍然在运行，但是占用的内存在持续地增长，大概每秒200-400MB。如果在自己的PC上跑的话，大概2-4秒内就会死机。

### 1.3 大致推断

Bug的现象是不断消耗内存，看起来像是在不断地递归，但是没有终点的感觉。

## 2 Bug 调试笔记

通过在源码中加`llvm::errs()`语句进行输出，来不断定位代码在哪里出问题。

####（1）

Executor.cpp中的executeInstruction()方法是klee对每条IR执行进行翻译和处理的函数，包含很多case，类似于语法解释器。

在这个方法的最开始部分，输出当前处理的指令的OpcodeName，发现是在执行一条Call语句时卡住的。

最后定位的结果，从executeInstruction()方法中调用了executeCall()方法。

#### （2）

在（1）的基础上，进入executeCall方法，添加`llvm::errs()`输出，定位到，这个方法`callExternalFunction()`方法，然后进入了`SpecialFunctionHandler::handle()`方法。

#### （3）

在Klee-1.4和Cloud9中的SpecialFunctionHandler::handle()方法中，同时加上`llvm::errs()`输出，可以观察到`Fuction syscall`在Klee-1.4中不在handels数组中，而在Cloud9中在handels数组中。

于是我们在`lib/Core/SpecialFunctionHandler.cpp`文件最上面往handels数组中添加内容的部分找到了`Fuction syscall`在Klee-1.4中不处理，而Cloud9添加了对它的处理。

在Cloud9新加的handlesyscall方法中，可能会调用callExternalFunction方法，于是进入（2），导致死循环。



## 3 解决办法

暂时的解决办法就是先把syscall的处理注释掉。